graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

    
spring:
  redis:
    database: 2
    host: localhost
    port: 6379
    #password: 936543rrds
    jedis:
      pool:
        max-active: 100
        max-wait: 2000
        max-idle: 500
        min-idle: 8
    timeout: 5000
seampl:
  data:
    hostname: http://localhost:8802
