env: gph
    
spring:
  redis:
    database: 2
    host: localhost
    port: 6379
    #password: 936543rrds
    jedis:
      pool:
        max-active: 100
        max-wait: 2000
        max-idle: 500
        min-idle: 8
    timeout: 5000
 rabbitmq:
    host: hdp-01
    port: 5672
    username: guest
    password: guest   

