spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_server_dev?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  application:
    name: auth-server
  redis:
    host: localhost
    database: 1
    port: 6379
  mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
  rabbitmq:
    host: hdp-01
    port: 5672
    username: guest
    password: guest
 
 env:
  dev
